job('First-Maven-Project-Via-DSL'){
	description("First Maven Project Generated by DSL on ${new Date()}")
	scm{
		git("https://github.com/tmatthysen/maven-samples-master.git", 'main')
	}
	triggers{
		scm('* * * * *')
	}
	steps{
	}

}